// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package capacitor

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *LogEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	_ = zb0001Mask
	if z.NodeID == "" {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.Value == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.Delta == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.TTL == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "s"
		o = append(o, 0xa1, 0x73)
		o = msgp.AppendUint64(o, z.Seq)
		// string "t"
		o = append(o, 0xa1, 0x74)
		o, err = z.TS.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "TS")
			return
		}
		// string "ba"
		o = append(o, 0xa2, 0x62, 0x61)
		o = msgp.AppendInt64(o, z.BornAt)
		// string "o"
		o = append(o, 0xa1, 0x6f)
		o, err = z.Op.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Op")
			return
		}
		// string "k"
		o = append(o, 0xa1, 0x6b)
		o = msgp.AppendString(o, z.Key)
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "n"
			o = append(o, 0xa1, 0x6e)
			o = msgp.AppendString(o, z.NodeID)
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "v"
			o = append(o, 0xa1, 0x76)
			o = msgp.AppendBytes(o, z.Value)
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "d"
			o = append(o, 0xa1, 0x64)
			o = msgp.AppendFloat64(o, z.Delta)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "ttl"
			o = append(o, 0xa3, 0x74, 0x74, 0x6c)
			o = msgp.AppendInt64(o, z.TTL)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LogEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "s":
			z.Seq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Seq")
				return
			}
		case "t":
			bts, err = z.TS.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "TS")
				return
			}
		case "ba":
			z.BornAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BornAt")
				return
			}
		case "o":
			bts, err = z.Op.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
		case "k":
			z.Key, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "n":
			z.NodeID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		case "v":
			z.Value, bts, err = msgp.ReadBytesBytes(bts, z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "d":
			z.Delta, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Delta")
				return
			}
		case "ttl":
			z.TTL, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LogEntry) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint64Size + 2 + z.TS.Msgsize() + 3 + msgp.Int64Size + 2 + z.Op.Msgsize() + 2 + msgp.StringPrefixSize + len(z.Key) + 2 + msgp.StringPrefixSize + len(z.NodeID) + 2 + msgp.BytesPrefixSize + len(z.Value) + 2 + msgp.Float64Size + 4 + msgp.Int64Size
	return
}
