// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package capacitor

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Batch) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "f":
			z.FromNode, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FromNode")
				return
			}
		case "e":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Entries")
				return
			}
			if cap(z.Entries) >= int(zb0002) {
				z.Entries = (z.Entries)[:zb0002]
			} else {
				z.Entries = make([][]byte, zb0002)
			}
			for za0001 := range z.Entries {
				z.Entries[za0001], err = dc.ReadBytes(z.Entries[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Entries", za0001)
					return
				}
			}
		case "h":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Handshake")
					return
				}
				z.Handshake = nil
			} else {
				if z.Handshake == nil {
					z.Handshake = new(Handshake)
				}
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Handshake")
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Handshake")
						return
					}
					switch msgp.UnsafeString(field) {
					case "ls":
						z.Handshake.LastSeenSeq, err = dc.ReadUint64()
						if err != nil {
							err = msgp.WrapError(err, "Handshake", "LastSeenSeq")
							return
						}
					case "at":
						z.Handshake.AuthToken, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Handshake", "AuthToken")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Handshake")
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Batch) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Handshake == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "f"
		err = en.Append(0xa1, 0x66)
		if err != nil {
			return
		}
		err = en.WriteString(z.FromNode)
		if err != nil {
			err = msgp.WrapError(err, "FromNode")
			return
		}
		// write "e"
		err = en.Append(0xa1, 0x65)
		if err != nil {
			return
		}
		err = en.WriteArrayHeader(uint32(len(z.Entries)))
		if err != nil {
			err = msgp.WrapError(err, "Entries")
			return
		}
		for za0001 := range z.Entries {
			err = en.WriteBytes(z.Entries[za0001])
			if err != nil {
				err = msgp.WrapError(err, "Entries", za0001)
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "h"
			err = en.Append(0xa1, 0x68)
			if err != nil {
				return
			}
			if z.Handshake == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				// check for omitted fields
				zb0002Len := uint32(2)
				var zb0002Mask uint8 /* 2 bits */
				_ = zb0002Mask
				if z.Handshake.AuthToken == "" {
					zb0002Len--
					zb0002Mask |= 0x2
				}
				// variable map header, size zb0002Len
				err = en.Append(0x80 | uint8(zb0002Len))
				if err != nil {
					return
				}

				// skip if no fields are to be emitted
				if zb0002Len != 0 {
					// write "ls"
					err = en.Append(0xa2, 0x6c, 0x73)
					if err != nil {
						return
					}
					err = en.WriteUint64(z.Handshake.LastSeenSeq)
					if err != nil {
						err = msgp.WrapError(err, "Handshake", "LastSeenSeq")
						return
					}
					if (zb0002Mask & 0x2) == 0 { // if not omitted
						// write "at"
						err = en.Append(0xa2, 0x61, 0x74)
						if err != nil {
							return
						}
						err = en.WriteString(z.Handshake.AuthToken)
						if err != nil {
							err = msgp.WrapError(err, "Handshake", "AuthToken")
							return
						}
					}
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Batch) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Handshake == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "f"
		o = append(o, 0xa1, 0x66)
		o = msgp.AppendString(o, z.FromNode)
		// string "e"
		o = append(o, 0xa1, 0x65)
		o = msgp.AppendArrayHeader(o, uint32(len(z.Entries)))
		for za0001 := range z.Entries {
			o = msgp.AppendBytes(o, z.Entries[za0001])
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "h"
			o = append(o, 0xa1, 0x68)
			if z.Handshake == nil {
				o = msgp.AppendNil(o)
			} else {
				// check for omitted fields
				zb0002Len := uint32(2)
				var zb0002Mask uint8 /* 2 bits */
				_ = zb0002Mask
				if z.Handshake.AuthToken == "" {
					zb0002Len--
					zb0002Mask |= 0x2
				}
				// variable map header, size zb0002Len
				o = append(o, 0x80|uint8(zb0002Len))

				// skip if no fields are to be emitted
				if zb0002Len != 0 {
					// string "ls"
					o = append(o, 0xa2, 0x6c, 0x73)
					o = msgp.AppendUint64(o, z.Handshake.LastSeenSeq)
					if (zb0002Mask & 0x2) == 0 { // if not omitted
						// string "at"
						o = append(o, 0xa2, 0x61, 0x74)
						o = msgp.AppendString(o, z.Handshake.AuthToken)
					}
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Batch) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "f":
			z.FromNode, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FromNode")
				return
			}
		case "e":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Entries")
				return
			}
			if cap(z.Entries) >= int(zb0002) {
				z.Entries = (z.Entries)[:zb0002]
			} else {
				z.Entries = make([][]byte, zb0002)
			}
			for za0001 := range z.Entries {
				z.Entries[za0001], bts, err = msgp.ReadBytesBytes(bts, z.Entries[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Entries", za0001)
					return
				}
			}
		case "h":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Handshake = nil
			} else {
				if z.Handshake == nil {
					z.Handshake = new(Handshake)
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Handshake")
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Handshake")
						return
					}
					switch msgp.UnsafeString(field) {
					case "ls":
						z.Handshake.LastSeenSeq, bts, err = msgp.ReadUint64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Handshake", "LastSeenSeq")
							return
						}
					case "at":
						z.Handshake.AuthToken, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Handshake", "AuthToken")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Handshake")
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Batch) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.FromNode) + 2 + msgp.ArrayHeaderSize
	for za0001 := range z.Entries {
		s += msgp.BytesPrefixSize + len(z.Entries[za0001])
	}
	s += 2
	if z.Handshake == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 3 + msgp.Uint64Size + 3 + msgp.StringPrefixSize + len(z.Handshake.AuthToken)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Handshake) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ls":
			z.LastSeenSeq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "LastSeenSeq")
				return
			}
		case "at":
			z.AuthToken, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AuthToken")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Handshake) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.AuthToken == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "ls"
		err = en.Append(0xa2, 0x6c, 0x73)
		if err != nil {
			return
		}
		err = en.WriteUint64(z.LastSeenSeq)
		if err != nil {
			err = msgp.WrapError(err, "LastSeenSeq")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "at"
			err = en.Append(0xa2, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteString(z.AuthToken)
			if err != nil {
				err = msgp.WrapError(err, "AuthToken")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Handshake) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.AuthToken == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "ls"
		o = append(o, 0xa2, 0x6c, 0x73)
		o = msgp.AppendUint64(o, z.LastSeenSeq)
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "at"
			o = append(o, 0xa2, 0x61, 0x74)
			o = msgp.AppendString(o, z.AuthToken)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Handshake) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ls":
			z.LastSeenSeq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastSeenSeq")
				return
			}
		case "at":
			z.AuthToken, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AuthToken")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Handshake) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint64Size + 3 + msgp.StringPrefixSize + len(z.AuthToken)
	return
}
