// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package capacitor

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "t":
			{
				var zb0002 byte
				zb0002, err = dc.ReadByte()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = MsgType(zb0002)
			}
		case "k":
			z.Key, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "v":
			z.Value, err = dc.ReadBytes(z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "d":
			z.Delta, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Delta")
				return
			}
		case "ttl":
			z.TTL, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		case "ts":
			z.Timestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "n":
			z.NodeID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	if z.Value == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Delta == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.TTL == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "t"
		err = en.Append(0xa1, 0x74)
		if err != nil {
			return
		}
		err = en.WriteByte(byte(z.Type))
		if err != nil {
			err = msgp.WrapError(err, "Type")
			return
		}
		// write "k"
		err = en.Append(0xa1, 0x6b)
		if err != nil {
			return
		}
		err = en.WriteString(z.Key)
		if err != nil {
			err = msgp.WrapError(err, "Key")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "v"
			err = en.Append(0xa1, 0x76)
			if err != nil {
				return
			}
			err = en.WriteBytes(z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "d"
			err = en.Append(0xa1, 0x64)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.Delta)
			if err != nil {
				err = msgp.WrapError(err, "Delta")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "ttl"
			err = en.Append(0xa3, 0x74, 0x74, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.TTL)
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		}
		// write "ts"
		err = en.Append(0xa2, 0x74, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.Timestamp)
		if err != nil {
			err = msgp.WrapError(err, "Timestamp")
			return
		}
		// write "n"
		err = en.Append(0xa1, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteString(z.NodeID)
		if err != nil {
			err = msgp.WrapError(err, "NodeID")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Message) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	if z.Value == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Delta == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.TTL == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "t"
		o = append(o, 0xa1, 0x74)
		o = msgp.AppendByte(o, byte(z.Type))
		// string "k"
		o = append(o, 0xa1, 0x6b)
		o = msgp.AppendString(o, z.Key)
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "v"
			o = append(o, 0xa1, 0x76)
			o = msgp.AppendBytes(o, z.Value)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "d"
			o = append(o, 0xa1, 0x64)
			o = msgp.AppendFloat64(o, z.Delta)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "ttl"
			o = append(o, 0xa3, 0x74, 0x74, 0x6c)
			o = msgp.AppendInt64(o, z.TTL)
		}
		// string "ts"
		o = append(o, 0xa2, 0x74, 0x73)
		o = msgp.AppendInt64(o, z.Timestamp)
		// string "n"
		o = append(o, 0xa1, 0x6e)
		o = msgp.AppendString(o, z.NodeID)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Message) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "t":
			{
				var zb0002 byte
				zb0002, bts, err = msgp.ReadByteBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = MsgType(zb0002)
			}
		case "k":
			z.Key, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "v":
			z.Value, bts, err = msgp.ReadBytesBytes(bts, z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "d":
			z.Delta, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Delta")
				return
			}
		case "ttl":
			z.TTL, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		case "ts":
			z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "n":
			z.NodeID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Message) Msgsize() (s int) {
	s = 1 + 2 + msgp.ByteSize + 2 + msgp.StringPrefixSize + len(z.Key) + 2 + msgp.BytesPrefixSize + len(z.Value) + 2 + msgp.Float64Size + 4 + msgp.Int64Size + 3 + msgp.Int64Size + 2 + msgp.StringPrefixSize + len(z.NodeID)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MsgType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 byte
		zb0001, err = dc.ReadByte()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MsgType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MsgType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteByte(byte(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MsgType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendByte(o, byte(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MsgType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 byte
		zb0001, bts, err = msgp.ReadByteBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MsgType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MsgType) Msgsize() (s int) {
	s = msgp.ByteSize
	return
}
